import type { Product } from "@/components/common/product-card"

export const sampleProducts: Product[] = [
  {
    id: "1",
    name: "Smartphone Pro Max",
    description: "El último smartphone con cámara de 108MP, pantalla OLED de 6.7 pulgadas y batería de larga duración.",
    price: 899.99,
    originalPrice: 1099.99,
    image: "/modern-smartphone-with-sleek-design.jpg",
    category: "Tecnología",
    inStock: true,
    rating: 4.8,
  },
  {
    id: "2",
    name: "Auriculares Inalámbricos",
    description: "Auriculares premium con cancelación de ruido activa y hasta 30 horas de batería.",
    price: 249.99,
    image: "/premium-wireless-headphones-black.jpg",
    category: "Audio",
    inStock: true,
    rating: 4.6,
  },
  {
    id: "3",
    name: "Laptop Gaming RGB",
    description: "Laptop para gaming con procesador Intel i7, RTX 4060, 16GB RAM y SSD de 1TB.",
    price: 1299.99,
    originalPrice: 1499.99,
    image: "/gaming-laptop-with-rgb-keyboard.jpg",
    category: "Computadoras",
    inStock: true,
    rating: 4.7,
  },
  {
    id: "4",
    name: "Smartwatch Deportivo",
    description: "Reloj inteligente resistente al agua con GPS, monitor cardíaco y más de 100 deportes.",
    price: 199.99,
    image: "/sport-smartwatch-with-black-band.jpg",
    category: "Wearables",
    inStock: false,
    rating: 4.4,
  },
  {
    id: "5",
    name: "Cámara Mirrorless 4K",
    description: "Cámara profesional con sensor full-frame, grabación 4K y estabilización de imagen.",
    price: 1899.99,
    image: "/professional-mirrorless-camera-black.jpg",
    category: "Fotografía",
    inStock: true,
    rating: 4.9,
  },
  {
    id: "6",
    name: "Tablet Pro 12.9",
    description: "Tablet profesional con pantalla Liquid Retina, chip M2 y soporte para Apple Pencil.",
    price: 799.99,
    originalPrice: 899.99,
    image: "/professional-tablet-with-stylus.jpg",
    category: "Tablets",
    inStock: true,
    rating: 4.5,
  },
  {
    id: "7",
    name: "Altavoz Bluetooth Portátil",
    description: "Altavoz resistente al agua con sonido 360°, 20 horas de batería y luces LED.",
    price: 89.99,
    image: "/portable-bluetooth-speaker-with-led-lights.jpg",
    category: "Audio",
    inStock: true,
    rating: 4.3,
  },
  {
    id: "8",
    name: "Monitor Gaming 27 4K",
    description: "Monitor gaming de 27 pulgadas, resolución 4K, 144Hz, HDR10 y tiempo de respuesta 1ms.",
    price: 449.99,
    image: "/gaming-monitor-27-inch-4k-display.jpg",
    category: "Monitores",
    inStock: true,
    rating: 4.6,
  },
  {
    id: "9",
    name: "Teclado Mecánico RGB",
    description: "Teclado mecánico para gaming con switches Cherry MX, iluminación RGB personalizable.",
    price: 129.99,
    originalPrice: 159.99,
    image: "/gaming-keyboard.jpg",
    category: "Accesorios",
    inStock: true,
    rating: 4.4,
  },
]

export const categories = [
  "Todos",
  "Tecnología",
  "Audio",
  "Computadoras",
  "Wearables",
  "Fotografía",
  "Tablets",
  "Monitores",
  "Accesorios",
]
